# Generated by Django 5.2 on 2025-04-20 23:25

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticketmessage_is_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=5, max_length=20, prefix='TKT-', unique=True, verbose_name='شناسه تیکت'),
        ),
    ]
